### PR TITLE
Add appendix + version

### PR DESCRIPTION
**Pull request by jorainer**
Sorry @kevinrue - seems you're also working on the same :)

### CODE REVIEW

**Comment by jorainer** [comment]
You can also savely ignore this and add your own version instead :)

**Comment by kevinrue** [comment]
argh ... lol ...
Well I see things in your PR that are not part of mine.
Perhaps I'll merge mine, and then in a separate one we can bring in some of your changes?

**Comment by kevinrue** [comment]
oh wait, maybe it's an artefact of the diff view on github, I thought you edited things in the introduction, but a broad comparison seems like you've just added the version. I'm not sure why github detects additions and deletions in the subsequent lines: 

image

**Comment by kevinrue** [comment]
Ahhhhh you've hard-wrapped the lines, now I get it!

**Comment by jorainer** [comment]
yep - my emacs does that automatically - I don't like lines longer than 80 character :)

**Comment by kevinrue** [comment]
OK, closing this for now, since we don't want multiple appendix chapters.
If you're keen to hard wrap everything, be my guest :)

As a general rule, I try to put one sentence per line, while keeping sentences relatively short, so that `git diff` is easy enough to read (one sentence edited = one addition/deletion in diff), while minimising the left/right scrolling.
It's not ideal, but I find the hard wrapping on sentences over multiple lines more challenging to track in `git diff` and also more painful to maintain when adding/removing bits of sentences.

**Pull request closed without merging**
