### PR TITLE
DESCRIPTION - fields level 2 (#27)

### PR DESCRIPTION
**Pull request by dcassol**

### CODE REVIEW

**Review by kevinrue — COMMENTED** [review]
OK. The PR itself looks great. However, you've committed to the `master` branch of your fork, which is going to get messy when the PR gets merged to the `master` branch of this repo, as the histories of the `master` branch will be different on this repo and your fork. Instead, you should really `git cherry-pick` your commit to a branch, and open a PR from that branch. That way, when the PR is merged your can safely delete your branch and update the `master` branch of your repository.
Better yet, since you have access to this repository, you could create a branch on this repository instead of working on your fork.

Let me know what you prefer!

**Comment by kevinrue** [comment]
I could also merge this PR as is, and you could delete your fork and fork again to get a clean copy of this updated repo, by the way

**Review by kevinrue — APPROVED** [review]
all good!

**Comment by dcassol** [comment]
I don't think is necessary to create another branch on my forked repo. If we `merge` now, I just `fetch` and `merge` the I will have everything updated, right?
Of course, I can use the strategy to create another branch in this repo, and in this case, after `merge`, just deleted the branch.

**Comment by kevinrue** [comment]
Sure, but the fetch and merge strategy will create additional commits on the master branch of your repository, which will eventually feed back in your future PRs.

**Pull request merged**
